version: '3.7'

services:

  server:
    environment:
      NODE_ENV: development
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_SESSION_SECRET: $REDIS_SESSION_SECRET
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server:/app/
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run pm2"]
