version: '3.7'

services:

  server:
    environment:
      - NODE_ENV=development
      - REDIS_SESSION_SECRET=$REDIS_SESSION_SECRET
      - MONGO_URI=mongodb://$DB_USER:$DB_PASS@mongo:27017
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server:/app/
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run pm2"]
