version: '3.7'

services:

  redis:
    build:
      context: ./redis
    ports:
      - 6379:$REDIS_PORT
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--requirepass", $REDIS_PASSWORD]

  server:
    build:
      context: ./server
    environment:
      HTTP_LOG_FORMAT: $HTTP_LOG_FORMAT
      NODE_ENV: $NODE_ENV
      PORT: $DEV_PORT
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_SESSION_SECRET: $REDIS_SESSION_SECRET
    ports:
      - 3000:$DEV_PORT
      - 9229:$DEBUG_PORT
    volumes:
      - ./server:/app/
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run pm2"]
    depends_on:
      - redis
