version: '3.7'

services:

  server:
    environment:
      NODE_ENV: production
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_SESSION_SECRET: $REDIS_SESSION_SECRET
    ports:
      - 3000:3000
      - 9229:9229
