version: '3.7'

services:

  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.selfsigned.crt:/etc/nginx/server.crt
      - ./nginx/localhost.selfsigned.key:/etc/nginx/server.key
    ports:
      - 443:443
    depends_on:
      - server

  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB_NAME

  redis:
    image: redis:5.0-alpine
    restart: always
    volumes:
      - /data

  server:
    build:
      context: ./server
    restart: always
    environment:
      - REDIS_URL=$REDIS_URL
    depends_on:
      - mongo
      - redis
