version: '3.7'

services:

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASS

  server:
    environment:
      NODE_ENV: development
      REDIS_SESSION_SECRET: $REDIS_SESSION_SECRET
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server:/app/
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run pm2"]
