version: '3.7'

services:

  redis:
    ports:
      - 6379:$REDIS_PORT
    volumes:
      - /data
    command: ["redis-server", "--port", $REDIS_PORT, "--requirepass", $REDIS_PASSWORD]

  server:
    build:
      context: ./server
    environment:
      NODE_ENV: development
      PORT: $NODE_SERVER_PORT
      DEBUG_PORT: $NODE_DEBUG_PORT
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_SESSION_SECRET: $REDIS_SESSION_SECRET
    ports:
      - 3000:$NODE_SERVER_PORT
      - 9229:$NODE_DEBUG_PORT
    volumes:
      - ./server:/app/
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run pm2"]
