version: '3.7'

services:

  nginx:
    image: nginx:1.17.8-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.selfsigned.crt:/etc/nginx/server.crt
      - ./nginx/localhost.selfsigned.key:/etc/nginx/server.key
    ports:
      - 443:443
    restart: always
    depends_on:
      - server

  redis:
    image: redis:5.0-alpine
    volumes:
      - /data

  server:
    build:
      context: ./server
    depends_on:
      - redis
